apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
spec:
  replicas: 5
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5000"
      labels:
        app: movies
    spec:
      containers:
        - name: movies
          image: adolfombarros/rotten-potatoes:v2
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_DB
              value: admin
            - name: MONGODB_HOST
              value: mongodb-service
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USERNAME
              value: mongouser
            - name: MONGODB_PASSWROD
              value: mongopwd

---

apiVersion: v1
kind: Service
metadata:
  name: movies-service
spec:
  selector:
    app: movies
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP
  #  nodePort: 30000
  #type: NodePort

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movies-ingress 
spec:
  rules:
  - host: movies.164.90.253.38.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: movies-service
            port: 
              number: 80